### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by iairose** [TomMitchell1/Watercolour-Generator#1]
jie@ubuntu:~/Watercolour-Generator$ python ./watercolour.py ./11.jpg
Traceback (most recent call last):
  File "./watercolour.py", line 167, in <module>
    main()
  File "./watercolour.py", line 144, in main
    neighbourhood_width = int(sys.argv[2])
IndexError: list index out of range

**Comment by TomMitchell1** [comment]
Hi,

This issue arises from how the program is executed, the program should execute similar to below.

python watercolour.py test.jpg 5

Where 5 is the neighbourhood width to be used during generation. I have added some checks to make sure that this value is specified and improved the documentation explain how to execute the program and what the neighbourhood width value does.
